### ISSUE TITLE
Do we have a demo site?

### ISSUE THREAD

**Issue by hsluoyz** [kowthalganesh/casbin-angular#1]

**Comment by kowthalganesh** [comment]
This repo is actually a demo site, along with all the setup needed for angular version are incorporated

**Comment by hsluoyz** [comment]
Yes. But I still expect a demo site, so users can understand it better.

You see how we publish the Casbin editor on GitHub pages: https://github.com/casbin/casbin-editor#deployment

I think we can publish it to GitHub pages too.

**Comment by kowthalganesh** [comment]
Oh, you mean I have to host this application some web server, I don't have any web server access so far. 
thought of user can clone the code in their local machine, they can up and run without any issue.

**Comment by hsluoyz** [comment]
No web server is required. GitHub pages is hosted by GitHub. All you need to do is modifying config in package.json

**Comment by hsluoyz** [comment]
See: https://github.com/casbin/casbin-editor/commit/42695091c4f515d7b10589b444e3fa3a244e1416

**Comment by kowthalganesh** [comment]
Okay, got an idea, will do the gh-pages config setup, and come back to you

**Comment by kowthalganesh** [comment]
https://kowthalganesh.github.io/casbin-angular/casbin-angular/

**Comment by hsluoyz** [comment]
Good!
